messages = [ 
            "Agradecimientos a Kheile por el soporte a la web oficial",
            "Te marcaste un Wil",
            "Es que no tengo cuerdas",
            "Como Coño Como",
            "Kasi la Bugeadora",
            "Tirar minas...",
            "El Tacones Neo", 
            "No le preguntes a neo porque no juega a raft...", 
            "agh1994 debe 5 euros a kasiri, recordale", 
            "Oscar_Qwery no acepta que es to pro en todo",
            "No le preguntes a fran sobre multicuentas...",
            "Lithuan el record guinness a muertes",
            "Mister Crasheos fran",
            "PERO TIIIIIIIIIIIIIIIIOOOOOOOOOO",
            "Me dan miedo los coches de policia",
            "Kheile mira Feo...", 
            "Solo se Minar",
            "Se cayo la antihordaaaaaa",
            "Decirle a neo como beber",
            "Ya no se que ponerle al bot, acepto sugerencias",
            "Me dan miedo los jabalis... preguntale a OQ49",
            "Clipero con mas de 1k clips -fran",
            "Aini no se compra el 7 days...",
            "No dejen a neo que vuele en giroscopio",
            "MurdermanX es muy majo",
            "Compren juegos En Eneba con en link de Kasiri",
            "FranNumeritos se desvela por desarollar el bot",
            "Isshune es muy maja",
            "what_a_Caravan",
            "No usen Hacks Cabritos",
            "Wil carrea, es muy bueno jugando",
            "¿Quien es EntityPlayer? Nadie lo sabra nunca",
            "TryhardeosOscar preguntenle sabe cosas",
            "Willy Un Tornado!!! que me pilla el tornado",
            "♪♪ Trabajo como un esclavo ♪♪",
            "No le pregunten a neo por el 'pasayo Disiclin'",
            "Neo no andes bloqueando las motos cabron",
            "Kasiri Tiene una pantera de verdad es malo..",
            "Come Paaaaaaaaaaaaaaan",
            "Roloooooooooooooooooooooo!!",
            "Capitan Ollie",
            "El neo es un perro pero no lo acepta",
            "Tengo 279 clips con Kasiri y contando...",
            "Kasiri Pa cuando Hollow Knight!?!?!",
            "Neo no seas cochino",
            "Tengo una pregunta... la pregunta es....",
            "Pareces Fran (mal sentido)",
            "Neo es calvo, siempre lleva peluca",
            "Se Cama!!! traduccion:'Se cae se mata'",
            "la dislexia ta potente",
            "Oscar me regaña mucho pero igual es compa",
            "El neo y fran comparten neuronas",
            "Quiero programar mi proyectoo!!!",
            "Tortillas de patata",
            "Por culpa del nombre de lithuan me dificulto programar las tablas de ranking, igual sin eso no me habria dado cuenta xD",
            "Las imagenes del bot son con IA pero estan guapas",
            "la idea del bot fue por el comando !miner",
            "el bot se llama 'Yuri Koteawa' es una minera experta",
            "pinguino - pinguino es Ninguino",
            "Ala Compra pan",
            "!Premioooooooooo",
            "A la mierda la Minita",
            "Soy Minita!! Soy minita Salvadme!",
            "Kasiri es la mamá de Todos",
            "Neo es el padre de Todos",
            "Tama Tama Tomate -by neo",
            "Kasiri eres to pro♬",
            "Kasiri es dislexica pero no lo acepta Kappa",
            "Si kasiri te enfoca estas muerto lo digo por experiencia",
            "Kheile es nuestro salvador, ayudo mucho a la web",
            "Tolon Tolon♬♬",
            "Viva el reino de Kasiri donde todos comemos pan",
            "Minito Abandonado",
            "No le pregunten a fran por 'Trampas_de_anarco' no le pregunten...",
            "El bot tiene lore, pero como soy perezoso aun no lo he escrito",  
            "Kasiri es experta en hacer una sopa blanca que era roja y se la puntuaron como 5 estrella a pesar que salio tod mal",
            "Jesucrito me contesta -by neo",
            "EXCLAMACION PLAY",
            "Kasi No te vayas ♬♬",
            "Kasi pa cuando las canicas? - No hay canicas?",
            "Neo destruyo toda la base en the forest por andar talando",
            "Kasi corta papatas con el mango del cuchillo",
            "a fran le encantan las piscinas de fuego",
            "Oscar hizo un drama por un dron",
            "MINITA COLGADA, MINITA EN EL QUINTO HUEVO",
            "agh1994 tuvo que quemar el pc para cerrar un juego",
            "Kasiri sabe hablar rata pero ya lo olvido",
            "Soy una ratillaa ♬♬",
            "SANFADAO?",
            "Por culpa de fran los comandos de sonidos tienen mas couldown",
            "Hablar con neo, es como hablar con una pared...",
            "Si quieres testear algo dile a 'Kasiri' Ella bugea hasta la sopa",
            "Mami quiero mi moto, me lo compras?",
            "Si lees esto eres calvo",
            "¿Kasiri puedo irme?, Kasiri:'No. no puedes. para que preguntas si ya sabes la respuesta'", #quitar
            "Sabes construir? no?, yo tampoco",
            "Oliver es el perrete de kasi, todos lo queremos",
            "Fran jugaba 7 days a 15 fps aun asi me divertia",
            "Kasiri sabia como duplicar tintes, lastima que ya lo parchearon",
            "Todos hablamos de wil y lo pro que es",
            "El equipo kasiri es muy fuerte",
            "Me dejaran unirme al equipo oscar?",
            "a Isshune le gustan las escopetas",
            "La nueva base del team Kasiri sera una caravana",
            "Fran es main escopetas ten cuidao",
            "Un dia quise escribir 'kasi la  escopeta', pero termine escribiendo 'kasila' asi nacio ese apodo",
            "Extraño el comando !ratilla",
            "おまえ わ もう しんでいる",
            "nutelear = 'tunelear y colgar'",
            "agh1994 es experto en chistes y hacer cohetes",
            "Tengo hambre -Fran",
            "habia un perro llamado pegamento, se cayo y se pego",
            "Fran crecio viendo a Kasiri",
            "lu neko nela",
            "El bot hice tematica de mineria porque me gusta minar",
            "Los traders del 7 days son bien estafadores pero igual les compramos",
            "El neo no tiene un pelo de tonto, literamente es calvo Kappa",
            "Fran ha tirado muchas minas y no fue queriendo",
            "llore mucho para que kasiri me diera mod -att fran",
            "a los 2 meses de llegar al canal de kasiri me dio Vip, me soprendio mucho",
            "El nombre 'Miner7days' se me ocurrio por la tematica de mineria y el juego, y porque \"Miner\" suena nice",
            "Este apartado de footer se hacen referencias y curiosidades del canal de kasiri y 7 days",
            "Que asco el arroz con platano",
            "Algo es algo dijo un calvo un pelo se peino",
            "El Neo(What_a_caramel), llego a hacer streams el twitch",
            "Neo suscribete al canal de Kasiri",
            "Kasiri antes se llamaba 'Kasiri93' porque 93? nose. bueno si se pero no te dire",
            "Kasiri-san omoshiroi hito desu",
            "Kasiri dropeo el juego 'A the Long Dark'",
            "Nose que poner, eso digo cuando nose que comentar en el chat.",
            "Me dicen franNumeritos para no decir los numeritos",
            "OQ49 tiene su serie \"7 days para principiantes\" si no sabes mucho le puede ser util",
            "je neko mish tomora",
            "habe prudenter",
            "OQ49 perdio en contra de un oso por no reparar sus armas en 7 days",
            "El Neo trolleo a todos con el dia 27, preguntele",
            "kasiri rusheo el Hytale por eso no lo juega",
            "El neo tiene una historia de un dinosaruio en el ARK",
            "Fran acepta sugerencias para agregarle al bot",
            "El comando '!miner' se supone que era consejos estupidos pero al final si son utiles",
            "Discord limita el diseño, eso me dio muchos dolores de cabeza",
            "lu neko nela",
            "tomlavik pek voluk",
            "La dislexia esta fuerte se nota en estos mensajes",
            "El neo dejo bloqueada una moto por una semana y nos mintio a todos",
            "Neo trollea hasta en la sopa",
            "Kasribot era el bot de kasiri para comandos pero ya no existe",
            "Kasiri juega la cooking simulator",
            "A Kasiri le encantan los juegos de pesca, regaladle un juego de eso",
            "Fran solo se divierte jugando 7 days",
            "what_a_caramel vendio a kasiri en una mision, acuerdenle",
            ]